import os as s
import time as t
import platform as p
def functionGraphicalOne():
    print("\n\n")
    print("\t\t╔══════════════════════════════════════════╗")
    print("\t\t║                                          ║")
    print("\t\t║                                          ║")
    print("\t\t║                                          ║")
    print("\t\t║                                          ║")
    print("\t\t║                                          ║")
    print("\t\t║                                          ║")
    print("\t\t║                                          ║")
    print("\t\t║                                          ║")
    print("\t\t║                                          ║")
    print("\t\t║                                          ║")
    print("\t\t║                                          ║")
    print("\t\t║                                          ║")
    print("\t\t║                                          ║")
    print("\t\t║                                          ║")
    print("\t\t║                                          ║")
    print("\t\t║                                          ║")
    print("\t\t║                                          ║")
    print("\t\t║                                          ║")
    print("\t\t╚══════════════════════════════════════════╝")

def functionGraphicalTwo():
    print("\n\n")
    print("\t\t╔══════════════════════════════════════════╗")
    print("\t\t║                                          ║")
    print("\t\t║                                          ║")
    print("\t\t║                                          ║")
    print("\t\t║                                          ║")
    print("\t\t║                                          ║")
    print("\t\t║                                          ║")
    print("\t\t║                                          ║")
    print("\t\t║                                          ║")
    print("\t\t║                                          ║")
    print("\t\t║                                          ║")
    print("\t\t║                                          ║")
    print("\t\t║                                          ║")
    print("\t\t║                                          ║")
    print("\t\t║                                          ║")
    print("\t\t║                                          ║")
    print("\t\t║   ██████████                             ║")
    print("\t\t║                                          ║")
    print("\t\t╚══════════════════════════════════════════╝")

def functionGraphicalThree():
    print("\n\n")
    print("\t\t╔══════════════════════════════════════════╗")
    print("\t\t║                                          ║")
    print("\t\t║                                          ║")
    print("\t\t║                                          ║")
    print("\t\t║     █                                    ║")
    print("\t\t║     █                                    ║")
    print("\t\t║     █                                    ║")
    print("\t\t║     █                                    ║")
    print("\t\t║     █                                    ║")
    print("\t\t║     █                                    ║")
    print("\t\t║     █                                    ║")
    print("\t\t║     █                                    ║")
    print("\t\t║     █                                    ║")
    print("\t\t║     █                                    ║")
    print("\t\t║     █                                    ║")
    print("\t\t║     █                                    ║")
    print("\t\t║   ██████████                             ║")
    print("\t\t║                                          ║")
    print("\t\t╚══════════════════════════════════════════╝")

def functionGraphicalFour():
    print("\n\n")
    print("\t\t╔══════════════════════════════════════════╗")
    print("\t\t║                                          ║")
    print("\t\t║                                          ║")
    print("\t\t║   ██████████████████████████████         ║")
    print("\t\t║     █                                    ║")
    print("\t\t║     █                                    ║")
    print("\t\t║     █                                    ║")
    print("\t\t║     █                                    ║")
    print("\t\t║     █                                    ║")
    print("\t\t║     █                                    ║")
    print("\t\t║     █                                    ║")
    print("\t\t║     █                                    ║")
    print("\t\t║     █                                    ║")
    print("\t\t║     █                                    ║")
    print("\t\t║     █                                    ║")
    print("\t\t║     █                                    ║")
    print("\t\t║   ██████████                             ║")
    print("\t\t║                                          ║")
    print("\t\t╚══════════════════════════════════════════╝")

def functionGraphicalFive():
    print("\n\n")
    print("\t\t╔══════════════════════════════════════════╗")
    print("\t\t║                                          ║")
    print("\t\t║                                          ║")
    print("\t\t║   ██████████████████████████████         ║")
    print("\t\t║     █   █                                ║")
    print("\t\t║     █  █                                 ║")
    print("\t\t║     █ █                                  ║")
    print("\t\t║     ██                                   ║")
    print("\t\t║     █                                    ║")
    print("\t\t║     █                                    ║")
    print("\t\t║     █                                    ║")
    print("\t\t║     █                                    ║")
    print("\t\t║     █                                    ║")
    print("\t\t║     █                                    ║")
    print("\t\t║     █                                    ║")
    print("\t\t║     █                                    ║")
    print("\t\t║   ██████████                             ║")
    print("\t\t║                                          ║")
    print("\t\t╚══════════════════════════════════════════╝")

def functionGraphicalSix():
    print("\n\n")
    print("\t\t╔══════════════════════════════════════════╗")
    print("\t\t║                                          ║")
    print("\t\t║                                          ║")
    print("\t\t║   ██████████████████████████████         ║")
    print("\t\t║     █   █                 █              ║")
    print("\t\t║     █  █                  █              ║")
    print("\t\t║     █ █                                  ║")
    print("\t\t║     ██                                   ║")
    print("\t\t║     █                                    ║")
    print("\t\t║     █                                    ║")
    print("\t\t║     █                                    ║")
    print("\t\t║     █                                    ║")
    print("\t\t║     █                                    ║")
    print("\t\t║     █                                    ║")
    print("\t\t║     █                                    ║")
    print("\t\t║     █                                    ║")
    print("\t\t║   ██████████                             ║")
    print("\t\t║                                          ║")
    print("\t\t╚══════════════════════════════════════════╝")

def functionGraphicalSeven():
    print("\n\n")
    print("\t\t╔══════════════════════════════════════════╗")
    print("\t\t║                                          ║")
    print("\t\t║                                          ║")
    print("\t\t║   ██████████████████████████████         ║")
    print("\t\t║     █   █                 █              ║")
    print("\t\t║     █  █                  █              ║")
    print("\t\t║     █ █                 █████            ║")
    print("\t\t║     ██                  █▓█▓█            ║")
    print("\t\t║     █                    ███             ║")
    print("\t\t║     █                                    ║")
    print("\t\t║     █                                    ║")
    print("\t\t║     █                                    ║")
    print("\t\t║     █                                    ║")
    print("\t\t║     █                                    ║")
    print("\t\t║     █                                    ║")
    print("\t\t║     █                                    ║")
    print("\t\t║   ██████████                             ║")
    print("\t\t║                                          ║")
    print("\t\t╚══════════════════════════════════════════╝")

def functionGraphicalEight():
    print("\n\n")
    print("\t\t╔══════════════════════════════════════════╗")
    print("\t\t║                                          ║")
    print("\t\t║                                          ║")
    print("\t\t║   ██████████████████████████████         ║")
    print("\t\t║     █   █                 █              ║")
    print("\t\t║     █  █                  █              ║")
    print("\t\t║     █ █                 █████            ║")
    print("\t\t║     ██                  █▓█▓█            ║")
    print("\t\t║     █                    ███             ║")
    print("\t\t║     █                     █              ║")
    print("\t\t║     █                     █              ║")
    print("\t\t║     █                     █              ║")
    print("\t\t║     █                     █              ║")
    print("\t\t║     █                     █              ║")
    print("\t\t║     █                                    ║")
    print("\t\t║     █                                    ║")
    print("\t\t║   ██████████                             ║")
    print("\t\t║                                          ║")
    print("\t\t╚══════════════════════════════════════════╝")

def functionGraphicalNine():
    print("\n\n")
    print("\t\t╔══════════════════════════════════════════╗")
    print("\t\t║                                          ║")
    print("\t\t║                                          ║")
    print("\t\t║   ██████████████████████████████         ║")
    print("\t\t║     █   █                 █              ║")
    print("\t\t║     █  █                  █              ║")
    print("\t\t║     █ █                 █████            ║")
    print("\t\t║     ██                  █▓█▓█            ║")
    print("\t\t║     █                    ███             ║")
    print("\t\t║     █                     █  █           ║")
    print("\t\t║     █                     █ █            ║")
    print("\t\t║     █                     ██             ║")
    print("\t\t║     █                     █              ║")
    print("\t\t║     █                     █              ║")
    print("\t\t║     █                                    ║")
    print("\t\t║     █                                    ║")
    print("\t\t║   ██████████                             ║")
    print("\t\t║                                          ║")
    print("\t\t╚══════════════════════════════════════════╝")

def functionGraphicalTen():
    print("\n\n")
    print("\t\t╔══════════════════════════════════════════╗")
    print("\t\t║                                          ║")
    print("\t\t║                                          ║")
    print("\t\t║   ██████████████████████████████         ║")
    print("\t\t║     █   █                 █              ║")
    print("\t\t║     █  █                  █              ║")
    print("\t\t║     █ █                 █████            ║")
    print("\t\t║     ██                  █▓█▓█            ║")
    print("\t\t║     █                    ███             ║")
    print("\t\t║     █                  █  █  █           ║")
    print("\t\t║     █                   █ █ █            ║")
    print("\t\t║     █                    ███             ║")
    print("\t\t║     █                     █              ║")
    print("\t\t║     █                     █              ║")
    print("\t\t║     █                                    ║")
    print("\t\t║     █                                    ║")
    print("\t\t║   ██████████                             ║")
    print("\t\t║                                          ║")
    print("\t\t╚══════════════════════════════════════════╝")

def functionGraphicalEleven():
    print("\n\n")
    print("\t\t╔══════════════════════════════════════════╗")
    print("\t\t║                                          ║")
    print("\t\t║                                          ║")
    print("\t\t║   ██████████████████████████████         ║")
    print("\t\t║     █   █                 █              ║")
    print("\t\t║     █  █                  █              ║")
    print("\t\t║     █ █                 █████            ║")
    print("\t\t║     ██                  █▓█▓█            ║")
    print("\t\t║     █                    ███             ║")
    print("\t\t║     █                  █  █  █           ║")
    print("\t\t║     █                   █ █ █            ║")
    print("\t\t║     █                    ███             ║")
    print("\t\t║     █                     █              ║")
    print("\t\t║     █                     ██             ║")
    print("\t\t║     █                       █            ║")
    print("\t\t║     █                        █           ║")
    print("\t\t║   ██████████                             ║")
    print("\t\t║                                          ║")
    print("\t\t╚══════════════════════════════════════════╝")

def functionGraphicalTwelve():
    print("\n\n")
    print("\t\t╔══════════════════════════════════════════╗")
    print("\t\t║                                          ║")
    print("\t\t║                                          ║")
    print("\t\t║   ██████████████████████████████         ║")
    print("\t\t║     █   █                 █              ║")
    print("\t\t║     █  █                  █              ║")
    print("\t\t║     █ █                 █████            ║")
    print("\t\t║     ██                  █▓█▓█            ║")
    print("\t\t║     █                    ███             ║")
    print("\t\t║     █                  █  █  █           ║")
    print("\t\t║     █                   █ █ █            ║")
    print("\t\t║     █                    ███             ║")
    print("\t\t║     █                     █              ║")
    print("\t\t║     █                    ███             ║")
    print("\t\t║     █                   █   █            ║")
    print("\t\t║     █                  █     █           ║")
    print("\t\t║   ██████████                             ║")
    print("\t\t║                                          ║")
    print("\t\t╚══════════════════════════════════════════╝")


def clear():
    if p.system() == "Windows":
        s.system("cls")
        s.system("color c")
        s.system("mode con cols=100 lines=50")
        s.system("title LE JEU DU PENDU")
    elif p.system() == "Linux":
        s.system("clear")


def functionExecute(errorValue):
    global listeExecute
    if type(errorValue) is int or type(errorValue) is float:
        clear()
        if errorValue == 1:
            functionGraphicalOne()
        elif errorValue == 2:
            functionGraphicalTwo()
        elif errorValue == 3:
            functionGraphicalThree()
        elif errorValue == 4:
            functionGraphicalFour()
        elif errorValue == 5:
            functionGraphicalFive()
        elif errorValue == 6:
            functionGraphicalSix()
        elif errorValue == 7:
            functionGraphicalSeven()
        elif errorValue == 8:
            functionGraphicalEight()
        elif errorValue == 9:
            functionGraphicalNine()
        elif errorValue == 10:
            functionGraphicalTen()
        elif errorValue == 11:
            functionGraphicalEleven()
        elif errorValue == 12:
            functionGraphicalTwelve()
        else:
            print("erreur")
    else:
        print("erreur")

